[package]
name = "my_goal_list"
version = "1.0.0"
authors = []

[addresses]
goallist_addr='7e6c77e8a392680df7199b12dd3882b6d1d5cbb1201a5147be574e03ab0ba4ae'

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
